
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santo-alpha-dep
  labels:
    app: santo-alpha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: santo-alpha
  template:
    metadata:
      labels:
        app: santo-alpha
    spec:
      containers:
        - name: cont1
          image: 187296253525.dkr.ecr.us-east-1.amazonaws.com/santo-alphaimage:30-402b134
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ENV
              value: "dev"

